<h1>Importações</h1>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import MetaTrader5 as mt5
import datetime
import numpy as np
mt5.initialize()
ativo ='WIN$N'
periodo = 63
data = pd.DataFrame(mt5.copy_rates_from_pos(ativo, mt5.TIMEFRAME_D1, 1, periodo))
data

,time,open,high,low,close,tick_volume,spread,real_volume
0,1699833600,121555.0,121660.0,120865.0,121615.0,4045251,5,15403370
1,1699920000,121575.0,124790.0,121550.0,124615.0,4370829,5,15513570
2,1700092800,124475.0,125830.0,124125.0,125830.0,4779619,5,17572742
3,1700179200,125835.0,126440.0,125465.0,125895.0,4168249,5,14846870
4,1700438400,126165.0,127115.0,125845.0,127100.0,3773003,5,13700890
...,...,...,...,...,...,...,...,...
58,1707264000,130650.0,130650.0,129555.0,130045.0,4187271,5,16214943
59,1707350400,129835.0,130195.0,127955.0,128280.0,4217358,5,16310533
60,1707436800,128600.0,129020.0,127575.0,128060.0,4208138,5,16164089
61,1707868800,129420.0,129770.0,128765.0,129200.0,2183336,5,8221856
62,1707955200,129465.0,129925.0,128985.0,129900.0,1299720,0,15318114

<h1>Probabilidade de fechar o GAP do dia anterior</h1>

In [2]:
# for abertura,maxima,minima,fechamento in list(data[['open','high','low','close']].values):
#     if abertura > fechamento
total,_=data.loc[((data['open']>data['close'].shift(1))&(data['low']<data['close'].shift(1)))|((data['open']<data['close'].shift(1))&(data['high']>data['close'].shift(1)))].shape
total

45

In [3]:
probabilidade = total/periodo
probabilidade
print(f'A probabildiade é de {round(probabilidade*100,2)}%, com base nos últimos {periodo} pregões.')

A probabildiade é de 71.43%, com base nos últimos 63 pregões.