# Importando dados

In [1]:
import pandas as pd 
import MetaTrader5 as mt5
mt5.initialize()
data = pd.DataFrame(mt5.copy_rates_from_pos("WIN$N", mt5.TIMEFRAME_D1, 0, 252))
data

C:\Users\Netinhoklz\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
C:\Users\Netinhoklz\AppData\Local\Temp\ipykernel_18584\3852708306.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

,time,open,high,low,close,tick_volume,spread,real_volume
0,1676505600,111540.0,112255.0,110075.0,112185.0,5191056,5,17201412
1,1676592000,111245.0,111635.0,110675.0,110695.0,4494864,5,14225643
2,1677024000,109885.0,109915.0,108275.0,108495.0,2595346,5,8540645
3,1677110400,109110.0,110365.0,108210.0,109175.0,4481678,5,15333457
4,1677196800,108600.0,109100.0,106805.0,107490.0,4019311,5,13928486
...,...,...,...,...,...,...,...,...
247,1708300800,130465.0,131065.0,130085.0,131035.0,2688908,5,10293979
248,1708387200,130395.0,132070.0,130085.0,132070.0,3971098,5,15930581
249,1708473600,131520.0,132245.0,131215.0,132245.0,4247261,5,15955988
250,1708560000,132950.0,133000.0,131820.0,132055.0,3936614,5,15201721
251,1708646400,132260.0,132480.0,130860.0,131155.0,716221,0,9206234

# Probabilidade de um dia ser ter a mesma direção (fechar positivo ou negativo) igual ao dia anterior

In [2]:
data['alta/baixa'] = [1 if data['close'].iloc[x] - data['open'].iloc[x]>0 else 0 for x in range(data.shape[0])]
gain = 0
for k in range(1,data.shape[0]):
    if data['alta/baixa'][k] == data['alta/baixa'][k-1]:
        gain+=1
print(f'Acertos: {gain}\nErros: {data.shape[0]-gain}\nProbabilidade de acerto: {gain/data.shape[0]}')

Acertos: 130
Erros: 122
Probabilidade de acerto: 0.5158730158730159