<h1>Importações</h1>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import MetaTrader5 as mt5
import datetime
import numpy as np
mt5.initialize()
ativo ='WDO$N'
data_10m = pd.read_excel('enor_grafico_10m.xlsx')
data = pd.DataFrame(pd.read_excel('graf_diario.xlsx'))
data['Amplitude_Vwap'] = abs(data['VWAP D'] - data['VWAP D'].shift(-1))
data['Amplitude'] = data['Máxima'] - data['Mínima']
data['media_amplitude'] = data['Amplitude'].rolling(22).mean()
data_10m

,Data,Abertura,Máxima,Mínima,Fechamento,VWAP D,VWAP S,VWAP M,Prior Cote,Prior Cote.1,Prior Cote.2,Prior Cote.3,Prior Cote.4
0,2023-09-29 09:00:00,5038.5,5038.5,5023.0,5031.5,5029.38,5012.06,4951.00,5034.5,5050.80,5015.5,5070.5,5070.5
1,2023-09-28 09:00:00,5040.0,5041.5,5030.0,5040.0,5035.87,4999.08,4943.40,5044.0,5057.00,4987.0,5079.5,5079.5
2,2023-09-27 09:00:00,4987.0,5006.5,4987.0,5004.5,4995.74,4970.52,4934.18,4989.5,4988.64,4954.0,4996.0,4996.0
3,2023-09-26 09:00:00,4977.0,4985.5,4971.5,4974.5,4978.27,4963.07,4930.81,4972.0,4973.37,4940.5,4978.0,4978.0
4,2023-09-25 09:00:00,4949.0,4953.0,4942.0,4942.0,4946.65,4946.65,4928.73,4940.5,4935.29,4908.5,4942.5,4942.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,2023-01-13 09:00:00,5129.5,5143.0,5127.5,5138.5,5134.67,5222.95,5223.90,5127.0,5100.60,5088.0,5206.5,5206.5
177,2023-01-12 09:00:00,5188.0,5195.5,5183.5,5192.5,5190.43,5256.85,5256.99,5182.5,5198.60,5181.0,5256.0,5256.0
178,2023-01-11 09:00:00,5224.5,5230.0,5212.5,5227.0,5220.77,5278.65,5277.68,5225.0,5233.71,5221.0,5300.0,5300.0
179,2023-01-10 09:00:00,5281.0,5300.0,5280.5,5285.5,5290.90,5300.69,5296.80,5281.0,5281.48,5271.5,5334.0,5334.0
180,2023-01-09 09:00:00,5305.0,5321.0,5279.5,5282.5,5300.62,5300.62,5274.97,5259.5,5269.64,5245.0,5397.5,5397.5

<h1>Probabilidade dele romper o candle de 10m para cima e para baixo </h1>

In [4]:
#Probabilidade dele romper o candle de 10m para cima e para baixo
contador_diario = 0
contador_10m = 0
rompeu_cima_e_baixo = 0
for data_9 in data_10m['Data']:
    for data_d in data['Data'][0:200]:
        if np.datetime64(data_9,'D') == np.datetime64(data_d,'D'):
            if data['Máxima'][contador_diario] > data_10m['Máxima'][contador_10m] and data['Mínima'][contador_diario] < data_10m['Mínima'][contador_10m]:
                rompeu_cima_e_baixo += 1
        contador_diario +=1
    contador_diario = 0 
    contador_10m+=1
print(rompeu_cima_e_baixo,rompeu_cima_e_baixo/181)

119 0.6574585635359116