# Estudo sobre a probabilidade de ter um valor maior que a mínima do último

In [28]:
import pandas as pd 
import MetaTrader5 as mt5
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
ativo = 'WIN$N'
mt5.initialize()

True

In [41]:
#TESTE INDICADOR FAZER O LEVANTAMENTO ESTATÍSTICO DE QUANTAS VEZES ELE BATE A META MÍNIMA DOS ÚLTIMOS 21 DIAS DE VOLATILIDADE
ticks_dias = pd.DataFrame(mt5.copy_rates_from_pos('WIN$N', mt5.TIMEFRAME_W1, 0, 63))

ticks_dias['time'] = pd.to_datetime(ticks_dias['time'],unit = 's')

ticks_dias['pmo_d-1'] = (ticks_dias['high'].shift(1) + ticks_dias['low'].shift(1))/2

ticks_dias['buscou_pmo_d-1'] = [1 if ticks_dias['low'].iloc[x] < ticks_dias['pmo_d-1'].iloc[x] < ticks_dias['high'].iloc[x] else 0 for x in range(0,ticks_dias.shape[0])]

ticks_dias

,time,open,high,low,close,tick_volume,spread,real_volume,pmo_d-1,buscou_pmo_d-1
0,2022-12-11,107895.0,107895.0,103095.0,104710.0,28941498,5,84336178,NaN,0
1,2022-12-18,105000.0,111825.0,104195.0,111430.0,27492919,5,79735907,105495.0,1
2,2022-12-25,111240.0,112850.0,108945.0,111035.0,18083762,5,50234335,108010.0,0
3,2023-01-01,110400.0,110815.0,104970.0,110600.0,25491093,5,75120139,110897.5,0
4,2023-01-08,109335.0,114190.0,108800.0,111990.0,26522115,5,79474348,107892.5,0
...,...,...,...,...,...,...,...,...,...,...
58,2024-01-21,128450.0,130215.0,126580.0,129325.0,20520762,5,79516496,130062.5,1
59,2024-01-28,129630.0,130060.0,126860.0,127580.0,21863259,5,84871721,128397.5,1
60,2024-02-04,127320.0,131110.0,126610.0,128060.0,20758916,5,80868564,128460.0,1
61,2024-02-11,129420.0,131165.0,128765.0,130830.0,10424794,5,39489111,128860.0,1
62,2024-02-18,130465.0,133000.0,130085.0,131130.0,15559293,0,66576255,129965.0,0

In [42]:
x = ticks_dias['buscou_pmo_d-1'].values

In [43]:
#Probabilidade:
quantidade = np.sum(x == 1)
print(f'Probabilidade: {quantidade/len(x)}')

Probabilidade: 0.6349206349206349